{
  "artifacts": [],
  "command": "my_main",
  "experiment": {
    "base_dir": "C:\\Users\\jonas\\Documents\\epymarl\\epymarl\\src",
    "dependencies": [
      "munch==2.5.0",
      "numpy==1.23.1",
      "sacred==0.8.2",
      "torch==2.0.1"
    ],
    "mainfile": "main.py",
    "name": "pymarl_0",
    "repositories": [
      {
        "commit": "579486f9fa2eb628e162ef4acf51e1cb1c24f42d",
        "dirty": true,
        "url": "https://github.com/JonasWild/epymarl.git"
      },
      {
        "commit": "579486f9fa2eb628e162ef4acf51e1cb1c24f42d",
        "dirty": true,
        "url": "https://github.com/JonasWild/epymarl.git"
      },
      {
        "commit": "579486f9fa2eb628e162ef4acf51e1cb1c24f42d",
        "dirty": true,
        "url": "https://github.com/JonasWild/epymarl.git"
      }
    ],
    "sources": [
      [
        "main.py",
        "_sources\\main_241fc96eda601c2b11588dda98a53d59.py"
      ],
      [
        "run.py",
        "_sources\\run_6df4177238aa94b24bef38e04727c0ac.py"
      ],
      [
        "utils\\logging.py",
        "_sources\\logging_0de701fe31cd6b451bd7edc16d5224fd.py"
      ]
    ]
  },
  "fail_trace": [
    "Traceback (most recent call last):\n",
    "  File \"C:\\Users\\jonas\\.conda\\envs\\pymarl\\lib\\site-packages\\sacred\\config\\captured_function.py\", line 42, in captured_function\n    result = wrapped(*args, **kwargs)\n",
    "  File \"C:\\Users\\jonas\\Documents\\epymarl\\epymarl\\src\\main.py\", line 146, in my_main\n    run(_run, config, _log)\n",
    "  File \"C:\\Users\\jonas\\Documents\\epymarl\\epymarl\\src\\run.py\", line 60, in run\n    run_sequential(args=args, logger=logger)\n",
    "  File \"C:\\Users\\jonas\\Documents\\epymarl\\epymarl\\src\\run.py\", line 192, in run_sequential\n    episode_batch = runner.run(test_mode=False)\n",
    "  File \"C:\\Users\\jonas\\Documents\\epymarl\\epymarl\\src\\runners\\episode_runner.py\", line 248, in run\n    self.logger.log_heatmaps(heatmaps)\n",
    "  File \"C:\\Users\\jonas\\Documents\\epymarl\\epymarl\\src\\utils\\logging.py\", line 54, in log_heatmaps\n    heatmaps = heatmaps + self.heatmap_dict.values()\n",
    "TypeError: can only concatenate list (not \"dict_values\") to list\n"
  ],
  "heartbeat": "2023-08-04T11:39:52.816381",
  "host": {
    "ENV": {},
    "cpu": "Unknown",
    "gpus": {
      "driver_version": "531.79",
      "gpus": [
        {
          "model": "NVIDIA GeForce GTX 960",
          "persistence_mode": false,
          "total_memory": 2048
        }
      ]
    },
    "hostname": "DESKTOP-1HDPUO6",
    "os": [
      "Windows",
      "Windows-10-10.0.22621-SP0"
    ],
    "python_version": "3.8.16"
  },
  "meta": {
    "command": "my_main",
    "options": {
      "--beat-interval": null,
      "--capture": null,
      "--comment": null,
      "--debug": false,
      "--enforce_clean": false,
      "--file_storage": null,
      "--force": false,
      "--help": false,
      "--loglevel": null,
      "--mongo_db": null,
      "--name": null,
      "--pdb": false,
      "--print-config": false,
      "--priority": null,
      "--queue": false,
      "--s3": null,
      "--sql": null,
      "--tiny_db": null,
      "--unobserved": false,
      "COMMAND": null,
      "UPDATE": [],
      "help": false,
      "with": false
    }
  },
  "resources": [],
  "result": null,
  "start_time": "2023-08-04T11:33:51.569870",
  "status": "FAILED",
  "stop_time": "2023-08-04T11:39:52.825886"
}